name: Run Tests

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3

    - name: Restore dependencies
      run: dotnet restore ./NetChallenge.Test/NetChallenge.Test.csproj

    - name: Build
      run: dotnet build ./NetChallenge.Test/NetChallenge.Test.csproj --no-restore

    - name: Test
      run: dotnet test ./NetChallenge.Test/NetChallenge.Test.csproj --no-build --verbosity normal